version: "3.9"
services:
  myapp:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    container_name: podb
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}